---
title: "Project Title"
subtitle: "INFO 526 - Project Final"
author: 
  - name: "Data Dazzlers"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "Project description"
format:
   html:
    code-tools: true
    code-overflow: wrap
    embed-resources: true
editor: visual
execute:
  warning: false
  echo: false
---

## Abstract

## **Why this dataset?**

Choosing the Tucson accident crash dataset for project is a decision rooted in both relevance and practicality. As students at the University of Arizona, located in the heart of Tucson, this dataset offers a unique opportunity to study a subject that directly impacts the community. Analyzing traffic collision data within the city not only allows us to apply the theoretical knowledge we've gained in our data analysis courses but also provides insights into urban safety and transportation issues that affect peers and fellow residents. This project is not just an academic exercise; it's a chance to contribute to a safer, more informed Tucson.

## **Objective**

Our project's primary goal is to develop a dynamic and user-friendly tool that offers detailed insights into the frequency, severity, and causes of traffic accidents across different times and locations in Tucson. By enabling various stakeholders, including city planners, policy-makers, local residents, and fellow students, to access and interact with our findings, we aspire to contribute to informed decision-making processes and the implementation of effective road safety measures.

## **Overall Project Plan**

1.  Data Preparation and Analysis :
    -   Begin with a thorough cleaning and pre-processing of the Tucson accident crash dataset to ensure accuracy and usability.
    -   Conduct a comprehensive analysis focusing on temporal trends (time of day, day of the week, months), spatial distribution (accident hotspots), and accident severity (fatalities, injuries).
2.  Development of Interactive Visualizations :
    -   Utilize R Shiny for the creation of an interactive dashboard, allowing users to filter and explore the data based on specific criteria (e.g., time period, accident severity).
    -   Implement Leaflet for interactive maps to display spatial data and identify accident hotspots within Tucson using the latitude and longitude coordinates in the dataset.
    -   Use ggplot2 and Plotly for creating dynamic and static visualizations that can be adjusted according to user input.
3.  Accessibility and User Experience :
    -   Design the dashboard with a focus on accessibility, ensuring that our visualizations are informative and usable for all.
    -   Incorporate user-friendly features, such as slicer to highlight key insights and facilitate understanding.
4.  Outreach and Impact :
    -   Plan to present our findings to local authorities and community groups to foster discussions on improving road safety.
    -   Publish our interactive dashboard online, making it accessible to the public for educational and awareness purposes.

## **Analysis Plan**

The primary objective of our project is to delve deep into the Tucson accident crash dataset to uncover underlying patterns and factors contributing to road accidents within Tucson. By leveraging the extensive data provided by the Tucson Police Department, we aim to analyze how various dimensions such as day, time, injury severity, number of fatalities, and type of violation are all related to each other.

The two specific questions we aim to answer are:

### Question 1

Members: Sanja Dmitrovic, Jiayue He, Vidhyananth Sivashanmugam

Does day of the week and/or time of day affect severity and the number of accidents?

Variables to use:

-   TimeOccu (time at which accident occurred)

-   Day (day of week accident occurred)

-   InjurySeverity (how serious the injury caused by accident was)

Some additional variables may be used such as:

-   OperatorImpaired (if the operator was impaired due to substances or other reasons)

-   OperatorDistracted (if the operator was distracted)

These variables may help us explore why certain days of the weeks or times of day lead to more accidents. For example, our hypothesis is that weekend nights would lead to more accidents due to more usage of drugs and alcohol by the driver. This factors could also explain why some accidents are more severe than others.

Plots to create: To answer this question, we plan to create daily and hourly time series plots to easily observe trends in accident frequency and injury severity. In the Shiny app, there can be a time series bar where the user drags the button and the plot shows the different numbers of accidents in different hours in a day and days in the week.

### Question 2

Members: Naitik Shah, Varun Soni, Mohammad Ali Farmani

What is the relationship between the type of violation (e.g., failure to yield, aggressive driving) and if the accident resulted in a fatality?

Variables to use:

-   FatalCollision (yes or no if accident resulted in fatality or not)

-   TotalFatalities (number of fatalities reported as an integer)

-   All Violation variables which report yes or no (i.e., ViolationSpeed, ViolationTooClose, ViolationTrafficControlDevice, ViolationTurning, ViolationWrongWay, ViolationLane, ViolationFailuretoYield, ViolationCrosswalk, ViolationAggressiveDriving).

Plots to create: For the Shiny app, we will create a series of stacked bar plots that show the number of accidents based the type of violation. Pie charts may be included to provide a high-level summary of the percentage of crashes per violation type.

In the end, we aim for the user to hover over various areas in Tucson and see the time series plots and bar plots that give insights to the questions posed above.

## **Conclusion**

With a deep commitment to applying our analytical skills for the betterment of our community, we believe that this project represents a meaningful opportunity to make a tangible difference in the area of road safety in Tucson. We are excited about the potential of our interactive spatiotemporal visualization tool to illuminate insights that can lead to positive changes in our community.
